BUILDDIR=buildDebug

if [ -d $BUILDDIR ] ; then
 rm -r $BUILDDIR/*
else
 mkdir $BUILDDIR
fi

cd $BUILDDIR && cmake ../ -DCMAKE_BUILD_TYPE=Debug \
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
-DUSE_BOOSTTESTING_DYNLINK=ON 

